### ISSUE TITLE
Infografia

### ISSUE THREAD

**Issue by javiern-778** [SistemasTecTlaxiaco/infografia-javiern-778#1]
[Obtencion de Requerimientos Tecnicas y Estrategias.pdf](https://github.com/SistemasTecTlaxiaco/infografia-javiern-778/files/8054739/Obtencion.de.Requerimientos.Tecnicas.y.Estrategias.pdf)

**Comment by IsraelNicolas61** [comment]
Calificación: 18%

**Comment by josealfredo79** [comment]
Bien echo y revisado
