### ISSUE TITLE
INFOGRA SOBRE LA INGENIERIA DE REQUISITOS

### ISSUE THREAD

**Issue by javiern-778** [SistemasTecTlaxiaco/infografia-javiern-778#2]
![I](https://user-images.githubusercontent.com/79878933/109920450-ecc5aa00-7c7f-11eb-8701-a05217dbcc6e.jpg)

**Comment by CarlosSD16** [comment]
muy buen trabajo solo en la combinación de colores lastima un poco al lector Calf:10

**Comment by CarlosSD16** [comment]
muy buen  trabajo en definiciones conceptos muy bien  solo en la combinación de colores calificacion:19

**Comment by josealfredo79** [comment]
Esta bien realizado y revisado.
